name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Wakatime table
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: 'update: wakatime'
          COMMIT_USERNAME: 'BotLunacub'
          COMMIT_EMAIL: 'BotLunacub@users.noreply.github.com'
          UPDATED_DATE_FORMAT: '%Y.%M.%D %H:%M:%S'
          SHOW_OS: "False"
